import { Provider } from 'react-redux';
import { useStore } from '../store';
import Head from 'next/head';
import { wrapper } from '../store';

import 'swiper/css/bundle';
import '../styles/globals.css';

const WrappedApp = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Booku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Component {...pageProps} />
    </>
  );
};

export default wrapper.withRedux(WrappedApp);
